name: Containerbuild

# on: [push]
on: 
  push:
    branches:
      - none
jobs:
  build:
    runs-on: ubuntu-latest
    container: 'node:current'

    steps:
    - run: | 
        cat /etc/*release
        node -v
        npm -v
      
    # - uses: actions/checkout@v1
    # - run: |
    #     npm ci
    #     npm run build
    #     npm test