name: Show Secrets

on:
  push:
    branches:
    - main
# on: 
#   push:
#     branches:
#       - none


jobs:
  build:
    name: Show the secret
    runs-on: ubuntu-latest
    steps:
      #SECRET_KEY 是您在仓库的Secrets栏中手动添加的secret
      - run: echo "My secret is: ${{toJson(secrets)}}"