name: Show Secrets

on:
  push:
    branches:
    - main

jobs:
  build:
    name: Show the secret
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo My secret is: ${{secrets.GITHUB_TOKEN}}