name: Conditional

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          make && make test
      - name: Publish Documentation
        run: |
          scripts/publish.sh
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        if: github.repository == 'ethomson/project' && github.event_name == 'push'