name: Build with CMake and Ninja

on: 
  push:
    branches:
      - none
# on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Dependencies (Linux)
      run: sudo apt-get install ninja-build
      if: matrix.os == 'ubuntu-latest'
    - name: Install Dependencies (Windows)
      run: choco install ninja
      if: matrix.os == 'windows-latest'
    - name: Install Dependencies (macOS)
      run: brew install ninja
      if: matrix.os == 'macos-latest'
    # - name: Get Sources
    #   uses: actions/checkout@v1
    - name: Setup CMake
      run: |
        mkdir "${{ runner.workspace }}/build"
        cd "${{ runner.workspace }}/build"
      # cmake $GITHUB_WORKSPACE -GNinja
      shell: bash
    - name: Build
      # run: cmake --build .
      run: cmake --version
      working-directory: ${{ runner.workspace }}/build      
    - name: Test
      # run: ctest -V
      run: ctest --version
      working-directory: ${{ runner.workspace }}/build