name: Container Matrix

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: 
        - 'debian:7'
        - 'debian:testing'
        - 'ubuntu:14.04'
        - 'ubuntu:devel'
        - 'centos:6'
        - 'centos:latest'
    container: ${{matrix.container}}

    steps:
    - run: | 
        cat /etc/*release