# test
name: FailFast-Example

on: [push]

jobs:
  Build:
    strategy:    
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}} #ubuntu系统环境
    steps:
    - name: Build
      run: uname -a
