# test
name: FailFast-Example

on: [push]

jobs:
  Build:
    strategy:    
      matrix:
        os: [ubuntu-latest,windows-latest,macos-latest]
      fail-fast: true
    runs-on: ${{matrix.os}} 
    steps:
    - name: Build
      run: free
