# test
name: FailFast-Example

on: [push]

jobs:
  Build:
    strategy:    
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{matrix.os}} 
    steps:
    - name: Build
      run: top
